name: Deploying Production Branch

on:
  push:
    branches:
      - prod
jobs:
  deploy:

    runs-on: [self-hosted, node-yarn-vm] 

    env:
      PM2_PROCESS_NAME: "node-yarn-prod"
      NODE_VERSION: "20"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: False
          path: prod-branch  
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ env.node-version }}

      - name: Install dependencies
        run: yarn install
        working-directory: prod-branch
 
      - name: Start or Reload the Application
        run: |
          if pm2 list | grep -q "$PM2_PROCESS_NAME"; then
            echo "Process $PM2_PROCESS_NAME exists. Reloading..."
            pm2 reload "$PM2_PROCESS_NAME"
          else
            echo "Process $PM2_PROCESS_NAME does not exist. Starting..."
            pm2 start "yarn start" --name "$PM2_PROCESS_NAME"
          fi
        working-directory: prod-branch
